### PR TITLE
Add nu_plugin_endecode

### PR DESCRIPTION
**Pull request by KAAtheWiseGit**
The `url` field is a subfolder in a larger repository, so I'm not sure if it'll work.  I copied the file path the way `gstat` does it.

### CODE REVIEW

**Comment by fdncred** [comment]
let's find out. thanks.

**Comment by fdncred** [comment]
Looks like something in this PR broke it the CI.
https://github.com/nushell/awesome-nu/actions/runs/10635329467/job/29484672796

**Comment by fdncred** [comment]
i fixed it by tweaking the yaml. the indention was wrong.

**Comment by fdncred** [comment]
ugh, it's still not right https://github.com/nushell/awesome-nu/blob/main/plugin_details.md but at least it's not failing the ci now

**Comment by fdncred** [comment]
I think it's because you link to a location that doesn't have a config.toml with the version information in it. maybe it should be https://codeberg.org/kaathewise/nu-plugin/src/branch/trunk

**Comment by fdncred** [comment]
nope, that wasn't it either. it would be good to get this fixed then you have time.

**Comment by KAAtheWiseGit** [comment]
Oops, lemme do that

**Pull request merged**
