### PR TITLE
Fix Codeberg path creation

### PR DESCRIPTION
**Pull request by KAAtheWiseGit**
Fixes the issues with Codeberg path creations, which broke the CI after #62

### CODE REVIEW

**Comment by fdncred** [comment]
I'm not really a fan of all the arms doing `return (blah)` and the codeberg part doing `blah | return $in`. Can you update it to have some consistency?

**Comment by KAAtheWiseGit** [comment]
Fixed

**Comment by fdncred** [comment]
ok, let's try it.

**Comment by fdncred** [comment]
doesn't look like it worked. i don't see your plugin in the list

**Comment by fdncred** [comment]
oops, i'm wrong. it's in the list. it just has no description.

**Comment by KAAtheWiseGit** [comment]
Yeah, the lack of the description is an issue on my end, I forgot to add it my Cargo manifest

**Pull request merged**
