### PR TITLE
fixed detailed plugin report

### PR DESCRIPTION
**Pull request by FMotalleb**
* Prevent crashing in case of an issue in the repository URL or branch name.
* The `workflow_dispatch` event has been added to the action so that it can be activated manually as needed.

### CODE REVIEW

**Comment by fdncred** [comment]
@FMotalleb I think we're getting rate limited now. Any solution to this?

```
Run hustcer/setup-nu@v3.8
versionSpec: 0.8[7](https://github.com/nushell/awesome-nu/actions/runs/7190225535/job/19583016365#step:2:8).0
coerce version: 0.[8](https://github.com/nushell/awesome-nu/actions/runs/7190225535/job/19583016365#step:2:9)7.0
Error: API rate limit exceeded for 20.10[9](https://github.com/nushell/awesome-nu/actions/runs/7190225535/job/19583016365#step:2:10).39.151. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

**Comment by FMotalleb** [comment]
Less than one a week? Is it a docker image from dockerhub? I'll check it soon

**Comment by fdncred** [comment]
I'm not quite sure what is going on. I haven't looked too deeply into it yet.

**Comment by FMotalleb** [comment]
@fdncred please check #35

**Comment by fdncred** [comment]
@FMotalleb Would you mind checking the script sometime? It's not working for some reason.

**Pull request merged**
