### PR TITLE
Fix rate limit issue

### PR DESCRIPTION
**Pull request by FMotalleb**
This should fix the issue with the rate limit problem mentioned by @fdncred

### CODE REVIEW

**Comment by fdncred** [comment]
Do I need to create some github token for this to work?

**Comment by FMotalleb** [comment]
> Do I need to create some github token for this to work?

As far as I know, GitHub automatically creates a unique GITHUB_TOKEN secret to use in your workflow.

**Comment by fdncred** [comment]
ok, let's try it. I can't remember if i can start this CI manually or not.

**Comment by fdncred** [comment]
cool. i was able to run it manually and it worked! thanks!

**Pull request merged**
